### ISSUE TITLE
tick and Joblib dependency on Python 3.8

### ISSUE THREAD

**Issue by RichardShea** [IdeasLabUT/CHIP-Network-Model#2]
To use 'tick' and 'Joblib' dependencies, I had to roll back to Python 3.6.  Then had to roll back to scikit-learn==0.21.2 for Joblib dependency.

Below are the steps I did in iTerm2 to create a conda enviroment to run all three notebooks in your example folder (I'm running JupyterLab 2.2.6 and Spyder 4.1.5 via Anaconda on Mohave OSX):

# Create a new conda environment
conda create --name py362 python=3.6.2
conda activate py362

########################################################################
# This section is only if you want to install the variable explorer extension in JupyterLab on Python 3.6.2:

# First..Completely install conda nodes.js:

conda install -c conda-forge nodejs
conda install -c conda-forge/label/gcc7 nodejs
conda install -c conda-forge/label/cf201901 nodejs
conda install -c conda-forge/label/cf202003 nodejs

# Now install extension:

jupyter labextension install @lckr/jupyterlab_variableinspector

########################################################################

# Run the following commands before running CHIP .ipynb examples:

conda install numpy
conda install matplotlib
conda install networkx
conda install joblib
pip install tick
conda install scikit-learn==0.21.2
conda install dill

# Good point to backup:

conda create --name py362clone --clone py362

# For Spyder
# If everything runs good in JupyterLab, now install Spyder 4.1.5

conda install -c anaconda spyder

# will need to convert .ipynb to .py for Spyder IDE usage

# For plots to show in JupyterLab or Spyder:
# Need to put this command in every cell before first plt. command:

%matplotlib inline

**Comment by Makan-Ar** [comment]
Hi Richard,

Due to several issues with the package `tick`, we removed it as a dependency and replaced its functionality with a Python/Numpy implementation.

For other packages' recommended version, please refer to the `requirements.txt`.

Thank you!
